#!/bin/sh
cd /recalbox/share/auto-resize
/bin/echo "Installing SD Card Resizer..."
/bin/mount -o remount,rw /
/usr/bin/find . -type f -print0 | xargs -0 chmod a+rx
/bin/cp -rp usr/* /usr/
/bin/mount -o remount,ro /
/bin/echo "Done!"
