#!/bin/sh
cd /recalbox/share/
wget --no-check-certificate https://github.com/Emulga/maintenance/raw/master/auto-resize/auto-resize.zip -O /recalbox/share/auto-resize.zip
/usr/bin/unzip auto-resize.zip
cd /recalbox/share/auto-resize
/bin/echo "Installing SD Card Resizer..."
/bin/mount -o remount,rw /
/usr/bin/find . -type f -print0 | xargs -0 chmod a+rx
/bin/cp -rp usr/* /usr/
/bin/mount -o remount,ro /
/bin/rm /recalbox/share/auto-resize.zip
/bin/rm -rf /recalbox/share/auto-resize/
/bin/echo "Done!"
/bin/echo ""
/bin/echo "Please type the following to begin resizing your Share Partition"
/bin/echo ""
/bin/echo "cd /"
/bin/echo ""
/bin/echo "emulga-resizeshare"
