#!/bin/sh
#
# Credit to RetroPie for including resize2fs in their releases
# https://retropie.org.uk/
# And without their effort this script wouldn't exist.
#
case "$1" in
  start)
    /usr/sbin/resize2fs /dev/mmcblk0p3
    mount -o remount,rw /
    rm /etc/init.d/S01resize2fs_once
    mount -o remount,ro /
    shutdown -r now
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
