#!/bin/sh
### BEGIN INIT INFO
# Provides:          resize2fs_once
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5 S
# Default-Stop:
# Short-Description: Resize the root filesystem to fill partition
# Description:
### END INIT INFO
case "$1" in
  start)
    /usr/sbin/resize2fs /dev/mmcblk0p3
    mount -o remount,rw /
    rm /etc/init.d/S01resize2fs_once
    mount -o remount,ro /
    shutdown -r now
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
